= May 2025 Plenary 

== Agenda

This Agenda will be lead by the GOM convenors with a brief discussion on each point and showing of online resources where indicated.

=== Agenda Outline

. *Welcome*
. *Reminder of the purpose of GOM*
. *Standards' Semantic Web review progress*
. *Standards' Semantic Web resource publication progress*
. *Discussion*
. *Next Meeting*

=== Agenda Details

. *Welcome*
.. Reminder of https://www.iso.org/publication/PUB100397.html[ISO Code of Conduct]
.. Meeting protocols
.. Roll call
... (re)introduction of co-chairs: Ivana & Nicholas
.. How to contribute/amend Agenda/Minutes
.. Start Recording
. *Reminder of the purpose of GOM*
. *Standards' Semantic Web review progress*
.. review process has been a placholder for the last 12 months
.. process to start becomeing "real" now that TC-211 Semantic Web publishing facility is available
.. ontology publication next step
.. Reg. Maintenance Group & GOM need to work together maintaining ongoing SemWeb publication
. *Standards' Semantic Web resource publication progress*


. *Discussion*
.. ISO Codelists now published in production
... see http://def.isotc211.org/codelists/



. *Progress on vocabulary publication (..will be updated..)* 
.. ISO Codelists now test published http://defs-dev.opengis.net/prez-hosted/catalogs/tc211:[on the OGC Rainbow's test system]
... ~50 codelists (of 200+) published for demo
... alongside other OGC vocabs and non-vocabs Semantic objects
.... example non-vocab object: https://demo.dev.kurrawong.ai/catalogs/phcat:buildingblocks/collections/ogcgh:ogc.geo.json-fg.feature[OGC Building Blocks Register: JSON-FG 'Feature']
... codelist (vocabulary) level metadata needs improvement for governance and display
... new metadata at the element (codelist item) level such as `status` already demonstrated, e.g. http://defs-dev.opengis.net/prez-hosted/catalogs/tc211:/collections/ns35:DS_AssociationTypeCode/items/dsassociationtypecode:collectiveTitle[Association Type code: collective title]
... TC-211 PIDs not yet in place - will proceed after plenary 
... Ontology publication - ISO19115 - not yet demonstrated
.... Ontology ready but system OGC system not ready
.... OGC will publish their own ontologies via the system, e.g. GeoSPARQL & CRS Ontology
.. proposed next steps
... complete publication of all codelists
... improve codelists' metadata & term display
.... consider better statuses, building on http://defs-dev.opengis.net/prez-hosted/catalogs/tc211:/collections/ns45:RE_ItemStatus[ISO19135 Status Codes]
... demo ISO-specific UI elements
.... ISO branding
.... ISO-specific content display - e.g. codelists' standards' applicability
... redirect PIDs to new system
... enable more export options - OASIS?
... replacement of shadow vocabs with these official published forms
.... Australian government, initial example https://linked.data.gov.au/def/data-roles[Data Role / ISO19115 Role Codes]
... publish ISO19115 ontology
... harmonisation of ISO19157-3 (DQ Measures) register of definitions with codelists
. *Discussion*


. *Next Meeting*
.. When: 
.. Proposed Agenda:
... TBD
